version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/Rails-Only/
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
    command: bash -c "sleep 10 && rm -f tmp/pids/server.pid && ./wait-for-it.sh db:3306 -- bundle exec rails s -p 3000 -b '0.0.0.0'"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Rails_Only_development
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data:
